# Generated by Django 6.1.1 on 2026-09-12 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccreditationCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nba_code', models.CharField(blank=True, max_length=50, null=True)),
                ('naac_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='KRAMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('activity_description', models.TextField()),
                ('target_type', models.CharField(choices=[('Numeric', 'Numeric'), ('Percentage', 'Percentage'), ('Boolean', 'Boolean')], max_length=20)),
                ('annual_target', models.CharField(max_length=100)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='core.accreditationcriteria')),
            ],
        ),
    ]
